### ISSUE TITLE
How to train the pre-trained checkpoint? For example, in VI-EN translation task.

### ISSUE THREAD

**Issue by TomasZhang19** [dmis-lab/AdvSR#1]
Could you please tell me how to train the pre-trained checkpoint? For example, in VI-EN translation task.

**Comment by JJumSSu** [comment]
I'm sorry for the late reply. Could you please elaborate more on your question? 
From my understanding, if you want to pre-train the checkpoint(not applying our method), then you can use fairseq or openNMT for training.

**Comment by TomasZhang19** [comment]
Thank you very much. I already use OpenNMT for the experiments.
